project:
  type: website
  output-dir: docs

website:
  title: "My Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: me.qmd
        text: About me
      - href: about.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: activities.qmd
        text: Activities


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

